### ISSUE TITLE
open edx: Gradebook import grades functionality doesn't work

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#415] opened 2022-02-15 20:12 UTC
### Helpful links

- Video overview explaining gradebook and the issue ([link](https://www.dropbox.com/s/72vpiwnwj96cflg/GradebookBulkImport_220215.mov?dl=0))
- Document with testing details ([link](https://docs.google.com/document/d/1OAaKrA6GjgIc79Idb4jfaZ9yg90RH-WzIwRaublvnCU/edit?usp=sharing))
- Some instructions ([link](https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/student_progress/course_grades.html#override-learner-subsection-scores-in-bulk))

### Steps to Reproduce

- Go to gradebook in edX (e.g. [link](https://courses-qa.mitxonline.mit.edu/gradebook/course-v1:MITx+14.73x+3T2021))
- Click Download Grades
- Open the downloaded file (ideally open it in a text editor rather than Excel in case Excel breaks things)
- Add a value to a `new-override` column ([instructions](https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/student_progress/course_grades.html#override-learner-subsection-scores-in-bulk))
- Save the file
- Use the import Grades button to import the updated file

### Expected Behavior

- The gradebook will update with the new grade(s) entered in the file

### Actual Behavior

- The gradebook doesn't update 

### Stacktrace / Additional info

- There is a 500 error in the browser
- A [Unicode-objects must be encoded before hashing](https://sentry.io/organizations/mit-office-of-digital-learning/issues/2948177777/?project=5939801&query=is%3Aunresolved) Sentry error is created
- Sar had some thoughts:

>    - Think the encoding is on the dev side. Ideally they shouldn’t really be using md5 at this point, but think it should be a one line fix to specify the encoding
>    - that’s what i think having briefly looked at it and jus tried running `md5.update` on the chunk in sentry
>    - When encoding is specified, it doesn’t throw the error

- Note that the edX gradebook code appears to be here: https://github.com/openedx/frontend-app-gradebook
### Screenshot or Screencast

- Video overview explaining gradebook and the issue ([link](https://www.dropbox.com/s/72vpiwnwj96cflg/GradebookBulkImport_220215.mov?dl=0))

**Comment by arslanashraf7** [comment] 2022-04-08 12:35
@blarghmatey Could you please confirm two things for me from our https://courses-qa.mitxonline.mit.edu instance?

1) I think we are running master, but can you confirm at which point/commit are we?
2) At which point are we for `frontend-app-gradebook`?

**Comment by blarghmatey** [comment] 2022-04-08 13:13
For QA we are now running from commit 97c58157f81b16d9a9da5fc91a413aa54229eea3 on frontend-app-learning and I just deployed a build from commit 62a95469d6399f8d93afe8d7d14088fe8f2b9939 of edx-platform

**Comment by arslanashraf7** [comment] 2022-04-28 10:08
Should we close this now @briangrossman ?

**Comment by pdpinch** [comment] 2022-05-17 12:57
@briangrossman can you test this in the overhang.io nutmeg test environment? If we can show the issue is happening there, I might be able to motivate someone to review Arslan's PR.

**Comment by pdpinch** [comment] 2022-06-02 18:53
According to Tobias, we should just need to add the appropriate pip git reference, like this one here: https://github.com/mitodl/ol-infrastructure/blob/main/src/bilder/images/edxapp/group_data/all.py#L53

We'd like to have this deployed to mitxonline and mitx, but if it's easier to add it to all of them, that would be fine too.

**Comment by arslanashraf7** [comment] 2022-06-03 11:50
The PR for above conversation is at https://github.com/mitodl/ol-infrastructure/pull/861

**Closed** 2023-01-30 03:23 UTC
