### ISSUE TITLE
open edX: update learning MFE to support PublicPath webpack setting

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#42] opened 2021-07-29 17:44 UTC
As a @mitodl/devops, I'd like to be able to route the learning MFE (frontend-app-learning) from a path on the lms server, instead of having to run it on a separate server. 

For other MFE's this was implemented by updating the version of frontend-platform and frontend-build used by the MFE, and making the route configurable in index.jsx. For example, see https://github.com/edx/frontend-app-gradebook/pull/145

It may also help to read https://discuss.openedx.org/t/deploying-mfes-in-the-community/

#### Acceptance Criteria:

- [x] fork https://github.com/edx/frontend-app-learning/ into the mitodl organization
- [ ] create a branch with the necessary changes
- [ ] test them on devstack by setting PublicPath and rebuilding frontend-app-learning with webpack
- [ ] alert @mitodl/devops so we can test on our QA deployment.
- [ ] open a PR on edx/frontend-app-learning -- I'm reasonably optimistic we can get this merged quickly

**Comment by pdpinch** [comment] 2021-07-30 18:02
To put this in a devstack context, if you run devstack master currently and access a course, it will be displayed through the Learning MFE (also known as frontend-app-learning) on port 2000. 

Instead of accessing the Learning MFE at `/` on port 2000, you should be able to configure it to run on the lms port (18000) at `/learn/` -- the same way you can configure the Gradebook MFE to run from https://localhost:18000/gradebook.

**Comment by arslanashraf7** [comment] 2021-08-12 12:59
To post an update:

While following the instructions mentioned in the PR and a few other documents e.g. [Technical Discovery Proposal](https://docs.google.com/document/d/1Wr6RkwZqiSm46fK-PQsY8D4dWNtHisw3QFEL8RyQLQs/edit#heading=h.vo2ywbxdhh5) I was able to run the gradebook at `localhost:1994/gradebook/<course_id>` but definitely not on something like ``localhost:18000/gradebook/<course_id>`` . What I did in the process mostly is:

- Setting up `PUBLIC_PATH='/gradebook/'` in [.env.development](https://github.com/edx/frontend-app-gradebook/blob/open-release/lilac.master/.env.development)
- Rebuilding the platform assets/webpack e.g, `make dev.static`

However when you mention
>the same way you can configure the Gradebook MFE to run from https://localhost:18000/gradebook

- Have we done it somewhere on any server e.g. https://lms-qa.mitxonline.mit.edu/ ? Are there any additional steps to above to run gradebook like `localhost:18000/gradebook` or maybe?
- Or maybe devops can put more light on running something `localhost:1994/gradebook/<course_id>` is fine and they can configure it to run on 18000 with the `/gradebook` path setup on, in which case I can configure the similar changes in `frontend-app-learning` making it run on a path something like `localhost:2000/learn/courses/<course_id>` which currently only runs on ``localhost:2000/courses/<course_id>``.

Additionally, I'm going to try and update [frontend-build](https://github.com/edx/frontend-build) to 7.0.0 or above which supports [public path setup using PUBLIC_PATH env](https://github.com/edx/frontend-build/blob/v7.0.0/config/webpack.dev-stage.config.js#L39) and see if it makes us able to run the MFE directly on `18000`.

More updates are to be posted soon.

CC: @pdpinch

**Comment by pdpinch** [comment] 2021-08-12 13:12
It's probably sufficient to get the MFE to deploy to `localhost:2000/learn/courses/<course_id>`, assuming you can configure devstack sufficiently to test. 

@shaidar can tell you more about how we are deploying the MFEs on QA and production. 

It might help to bring up the issue of how to develop and test path-based deployments in devstack (and/or Tutor) on discuss.edx.org. There's a [very long thread about the initial creation of this feature](https://discuss.openedx.org/t/deploying-mfes-in-the-community/2868/26), but I find it too complex to follow.

**Comment by blarghmatey** [comment] 2021-08-12 13:41
Correct, we don't need for the MFE to be accessible on the same port as the LMS, we just need to be able to specify a path where it is located. In our Fastly configuration we will be able to conditionally serve the assets from S3 at those paths but with the same domain as the LMS.

**Comment by arslanashraf7** [comment] 2021-08-12 14:50
Thanks for adding the details, Based on above, it makes sense to configure the `frontend-app-learing` to be accessible at `localhost:2000/learn/course/<course_id>` which currently runs `localhost:2000/course/<course_id>`. 

I will make the required changes for the path to be configurable based on `PUBLIC_PATH` env e.g. something like https://github.com/edx/frontend-app-gradebook/pull/145 so that `frontend-app-learning` could run on `localhost:2000/learn/course/<course_id>`.

**Comment by arslanashraf7** [comment] 2021-08-16 12:36
@pdpinch,

Here are some additional details:

I looked more into the `index.jsx` implementation of [frontend-app-learning](https://github.com/edx/frontend-app-learning/blob/master/src/index.jsx#L33) which uses the [AppProvider](https://github.com/edx/frontend-platform/blob/master/src/react/AppProvider.jsx) component from `frontend-platform` and it turns out that the public path is already supported in it and it won’t need similar changes like [this gradebook PR](https://github.com/edx/frontend-app-gradebook/pull/145)(These changes in grade book `index.jsx` were actually a workaround because it is using `IntlProvider from react-intl` instead of `AppProvider` component from `frontend-platform` unlike other MFEs -- [here](https://github.com/edx/frontend-app-gradebook/pull/145#issuecomment-724306085) is the link for this workaround in gradebook)

For some of the other MFEs which were using AppProvider, they only needed frontend-build and frontend-platform version bumps for them to support path-based routing e.g. [frontend-app-profile](https://github.com/edx/frontend-app-profile/pull/386), [frontend-app-account](https://github.com/edx/frontend-app-account/pull/340/). The required ` frontend-platform>=1.6.1` and ` frontend-build>=5.3.2` are already done in lilac & master of frontend-app-learning.

Based on the above I think we might not need any specific change in `frontend-app-learning`. I was also able to run the MFE directly without the changes we thought would be required for supporting path-based routing e.g. https://github.com/mitodl/frontend-app-learning/pull/1 (This PR now becomes invalid).

_Local changes I did to run `frontend-app-learning` at `localhost:2000/learn/course/<course_id>`_

1. Set `PUBLIC_PATH` variable to ‘/learn’ in `.env.development` — This will be set in `.env` in the production
2. Rebuild the MFE webpack (you could simply run `make dev.static.lms`)
3. Restart the frontend-app-learning container to reload the above change e.g. — `docker-compose restart frontend-app-learning`

Other changes that might be needed for redirect support are with idx-platform:

1. Setting https://github.com/edx/edx-platform/blob/master/lms/envs/common.py#L4639 to the URL of the MFE e.g. http://localhost:2000/learn in my case after setting PUBLIC_PATH to ‘/learn/’ (This will make sure that upon clicking on a course, the details are opened in the learning MFE )
2. There are other settings as well for e.g. setting `WRITABLE_GRADEBOOK_URL`  to open the gradebook from instructor page value for example.


**Testing:**
I tested it with the current master of edX and Lilac and `frontend-app-learning` with path-based routing is working. Attaching a screenshot of it working on `/learn`:
<img width="1440" alt="Screenshot 2021-08-16 at 5 08 06 PM" src="https://user-images.githubusercontent.com/34372316/129561667-5392394e-552b-4afb-a1c4-4509ab741fbe.png">

**Comment by pdpinch** [comment] 2021-08-16 15:07
Wow, thanks @arslanashraf7. That's unexpected. 

Do you know when this change was made? I just want to make sure that we have the right version in our deployment.

**Comment by arslanashraf7** [comment] 2021-08-16 15:53
@pdpinch The specifically required or above version upgrades were done in the below PRs:

- For `frontend-build` it was upgraded in [This PR](https://github.com/edx/frontend-app-learning/pull/247/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R65)
- For `frontend-platform` it was upgraded in [This PR](https://github.com/edx/frontend-app-learning/pull/283/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R40)
- And as [mentioned](https://github.com/edx/frontend-app-gradebook/pull/145#issuecomment-724306085) in the gradebook PR we were referring to, the `frontend-app-learning` is already using `AppProvider` right from the start.

As a matter of fact, all of the above changes are part of the [lilac release](https://github.com/edx/frontend-app-learning/blob/open-release/lilac.master/package.json) of `frontend-app-learning` already and I was able to test the routing on lilac as well where after setting the `PUBLIC_PATH='/learn/'` enabled me to load the learning MFE on `localhost:2000/learn/course/<course_id>`. 

I'm not sure if we tried the lilac release of this MFE or there is something else to this that I might be missing?

**Comment by arslanashraf7** [comment] 2021-08-16 15:57
Also just to add more, there is [this PR](https://github.com/edx/configuration/pull/6088#issuecomment-724305542) specific to `edx/configurations` that added the support for subdirectories support.

**Comment by blarghmatey** [comment] 2021-08-24 16:50
This has been confirmed working for RC and production. Closing.

**Closed by blarghmatey** 2021-08-24 16:50 UTC
