### ISSUE TITLE
enrollment failing for some users

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1395] opened 2023-01-27 13:28 UTC
### Steps to Reproduce

1. Hijack my account https://mitxonline.mit.edu/admin/users/user/?q=peter-pinch
2. navigate to, for example, https://mitxonline.mit.edu/courses/course-v1:MITxT+10.50.CH02x/
3. Try to enroll

### Expected Behavior

- I should be enrolled in the course
- I should see the success banner

### Actual Behavior

- I'm not enrolled
- I get a banner with the message "Something went wrong with your enrollment. Please contact support at mitxonline-support@mit.edu."
- I find it odd that there doesn't seem to be an error response to any of the API requests (see screenshot) 

### Stacktrace

Possibly related sentry event: https://sentry.io/organizations/mit-office-of-digital-learning/issues/3826849409/events/185595dd17c045dab9384b0ce2984a40/?project=5864687

Note that I'm not the only user getting this error.

### Screenshot or Screencast

<img width="1690" alt="image" src="https://user-images.githubusercontent.com/430126/215097937-1f756566-9025-4182-82fd-b596f59e48eb.png">

**Comment by jkachel** [comment] 2023-01-27 20:24
Looked at this and at least in the case for your username, I found the following: 
- There was an OpenEdxApiAuth record for the `peter-pinch` account with a refresh and access token. The access token had expired in December; the refresh tokens are longer-lived. 
- Attempting to enroll in a course (MITxT+10.50.CH07x+1T2023) failed and the HTTP 400 error was recorded in Sentry again: https://sentry.io/organizations/mit-office-of-digital-learning/issues/3826849409/events/8f5bab0ae0a348989fc03bb6003d9f5a/?project=5864687
- I then dropped into a Django shell and tried to just get an edx client object through `openedx/api.py` manually and got the same 400 error. This wasn't performing any operation - just setting up a client with a session to do things with. However, it will try to refresh an expired access token if it runs into one. 
- Thinking on that process, I checked in LMS admin for the refresh token that MITx Online had stored and could not find it. There was also no matching access token. So, at this point, the problem is that the authentication tokens somehow got wiped out on the edX side of things, and MITx Online was seeing a token and trying to use it (and then failing for obvious reasons). 

I deleted the OpenEdxApiAuth record that was there and ran `repair_missing_courseware_records --user peter-pinch` and then tried the enrollment again. It succeeded this time.

I found 5 other users that I could see in Sentry that have the same error. Those are failing for a similar but distinct reason - their refresh codes have been revoked in edX, so when it goes to refresh the tokens, edX denies that request.

I think we can maybe amend the process to try to recreate auth tokens once if the enrollment fails due to a HTTP 400 error. (The token creation process takes a sec so maybe that gets queued and processed via Celery.) I'm a bit concerned about the revoked tokens, though; I'm not sure why a refresh token would be revoked. Creating a new API token via the normal method (delete MITxOnline's copy, force it to repair) works if the refresh token was revoked, though.

**Closed** 2023-02-03 20:58 UTC
Labels: bug
